# Generated by Django 3.0.8 on 2020-07-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='active',
        ),
    ]
